import{useEffect,useMemo,useState}from"react";import{useNavigate}from"react-router-dom";import{useTaskStore}from"../../stores/taskStore";import{useWeatherStore}from"../../stores/weatherStore";import{useMusicStore}from"../../stores/musicStore";import{useFocusStore}from"../../stores/focusStore";import{localDateKey}from"../../utils/date";
const menu=[["⌂","Home","/"],["♙","Quest","/today"],["▦","Calendar","/calendar"],["☑","Todo","/today"],["▤","Note","/notes"],["▧","Photo","/gallery"],["♫","Music","/music"],["▥","Library","/notes"],["●","Map","/"],["▣","Archive","/gallery"],["⚙","Setting","/settings"]];
export function FantasyHome(){const nav=useNavigate(),[now,setNow]=useState(new Date()),tasks=useTaskStore(s=>s.tasks),toggle=useTaskStore(s=>s.toggleTask),weather=useWeatherStore(s=>s.snapshot),load=useWeatherStore(s=>s.load),music=useMusicStore(),focus=useFocusStore();useEffect(()=>{const x=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(x)},[]);useEffect(()=>{load()},[load]);const list=useMemo(()=>tasks.filter(t=>t.date===localDateKey(now)&&!t.deletedAt).slice(0,7),[tasks,now]),done=list.filter(t=>t.completed).length,first=new Date(now.getFullYear(),now.getMonth(),1).getDay(),days=new Date(now.getFullYear(),now.getMonth()+1,0).getDate();return <section className="fantasy-home">
 <nav className="fantasy-nav"><header>Our Day<small>A Brighter<br/>You<br/>Today.</small></header>{menu.map(([i,n,p])=><button className={n==="Home"?"active":""} onClick={()=>nav(p)} key={n}><b>{i}</b>{n}</button>)}<footer>Small<br/>Steps<br/>Make<br/>A Big<br/>Story.</footer></nav>
 <article className="fantasy-clock parchment"><small>{now.toLocaleDateString("en-CA").replaceAll("-",". ")} · {now.toLocaleDateString("en-US",{weekday:"short"}).toUpperCase()}</small><strong>{now.toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"})}</strong><p>“ 지금도 충분히 잘하고 있어. ”</p><b>A BRIGHTER YOU TODAY.</b></article>
 <article className="fantasy-weather" onClick={()=>load(true)}><header>Seoul</header><div/><strong>{weather?.temperature??24}°C</strong><b>{weather?.description??"맑음"}</b><small>H:{weather?.high??26}°　L:{weather?.low??18}°</small><p>The night is still<br/>a part of your day.</p></article>
 <article className="fantasy-music parchment"><div/><section><b>{music.title||"A Better Day"}</b><span>{music.artist||"IU"}</span><em><i style={{width:`${Math.max(35,music.progress)}%`}}/></em><footer><button>◀</button><button onClick={music.togglePlay}>{music.playing?"Ⅱ":"▶"}</button><button onClick={()=>nav("/music")}>▶</button></footer></section><strong>♥</strong><p>좋은 음악이<br/>오늘을 더 특별하게.</p></article>
 <aside className="fantasy-window"><p>Different<br/>Days,<br/>Same You.</p><b>Good Habits<br/>Better Mind<br/>Lovely Life</b></aside>
 <article className="fantasy-quest parchment"><header>Today's Quest <span>{done}/{list.length}</span></header>{list.map((t,i)=><button onClick={()=>toggle(t.id)} className={t.completed?"done":""} key={t.id}><i>{t.completed?"✓":["♣","♥","♦","□","♧","♜","♟"][i]}</i>{t.title}</button>)}<footer>작은 하루들이<br/>특별한 미래를 만든다.　✒</footer></article>
 <article className="fantasy-calendar"><header>‹　 {now.getFullYear()}. {now.getMonth()+1}　 ›</header><div>{["일","월","화","수","목","금","토"].map(x=><b key={x}>{x}</b>)}{Array.from({length:first}).map((_,i)=><i key={i}/>)}{Array.from({length:days},(_,i)=>i+1).map(d=><span className={d===now.getDate()?"today":""} key={d}>{d}</span>)}</div><p>좋은 날이 더 많기를. ♡</p></article>
 <article className="fantasy-note parchment" onClick={()=>nav("/notes")}><header>Today's Note　📜</header><p>오늘도<br/>수고했어.<br/>내일은 더 좋은<br/>날이야. ♡</p></article>
 <article className="fantasy-apps"><header>Quick Access</header>{[["▶","유튜브","/music"],["◎","인스타그램","/gallery"],["N","네이버","/"],["✉","메일","/notes"],["▲","드라이브","/gallery"],["◆","지도","/"],["◉","ChatGPT","/"],["＋","추가","/settings"]].map(([i,n,p])=><button key={n} onClick={()=>nav(p)}><b>{i}</b><span>{n}</span></button>)}</article>
 <article className="fantasy-focus"><header>Focus Timer</header><strong>{focus.active?`${Math.floor(focus.remainingSeconds()/60)}:${String(focus.remainingSeconds()%60).padStart(2,"0")}`:"25:00"}</strong><button onClick={()=>focus.start(25,"Magic Focus")}>▶</button><p>◎　Focus<br/>♨　Short Break<br/>☾　Long Break</p></article>
 <footer className="fantasy-map parchment"><header>Life Map</header><i>Every day<br/>is a new page.</i><div>{[["기상","☘"],["계획","♙"],["집중","♨"],["실행","⚔"],["휴식","♣"],["성장","✦"],["행복","♨"]].map(([n,x])=><span key={n}><b>{x}</b>{n}</span>)}</div></footer>
 </section>}
