import {useEffect,useMemo,useState} from "react";import{useNavigate}from"react-router-dom";import{useMusicStore}from"../../stores/musicStore";import{useTaskStore}from"../../stores/taskStore";import{useWeatherStore}from"../../stores/weatherStore";import{localDateKey}from"../../utils/date";
const W=["일","월","화","수","목","금","토"];
export function IsometricHome(){const nav=useNavigate(),[now,setNow]=useState(new Date()),tasks=useTaskStore(s=>s.tasks),toggle=useTaskStore(s=>s.toggleTask),weather=useWeatherStore(s=>s.snapshot),load=useWeatherStore(s=>s.load),music=useMusicStore();useEffect(()=>{const i=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(i)},[]);useEffect(()=>{load()},[load]);const key=localDateKey(now),list=useMemo(()=>tasks.filter(x=>x.date===key&&!x.deletedAt).slice(0,7),[tasks,key]),done=list.filter(x=>x.completed).length,first=new Date(now.getFullYear(),now.getMonth(),1).getDay(),days=new Date(now.getFullYear(),now.getMonth()+1,0).getDate();return <section className="iso-home">
 <div className="iso-world"><div className="iso-main-island"><i className="iso-house"/><i className="iso-trees"/><i className="iso-fall"/><b>GOOD<br/>ROUTINE</b></div><div className="iso-top-island"><i/><b>MY<br/>SPACE</b><span>BETTER<br/>ME</span></div><div className="iso-light-island"><i/><b>♜</b></div><div className="iso-small-island"/></div>
 <article className="iso-clock"><small>Good<br/>Things<br/>Take<br/>Time ♡</small><strong>{now.toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"})}</strong><b>{now.toLocaleDateString("ko-KR",{month:"long",day:"numeric",weekday:"long"})}</b><p>오늘도<br/>좋은 하루가 될 거야. ♡</p></article>
 <article className="iso-glass iso-weather" onClick={()=>load(true)}><div><span>{weather?.locationLabel||"서울특별시"}</span><b>🌤️　<strong>{weather?.temperature??25}°</strong></b><small>{weather?.description||"맑음"}　|　체감 {weather?.apparentTemperature??24}°</small></div><p>좋은 일이<br/>오늘도<br/>네 곁에 있기를. ♡</p></article>
 <nav className="iso-glass iso-nav">{[["⌂","Home","/"],["☑","Todo","/today"],["▣","Calendar","/calendar"],["▤","Note","/notes"],["◎","Focus","/focus"],["▥","Stats","/today"],["▧","Gallery","/gallery"],["⚙","Settings","/settings"]].map(([i,n,p])=><button className={n==="Home"?"active":""} key={n} onClick={()=>nav(p)}><b>{i}</b>{n}</button>)}</nav>
 <article className="iso-player"><div className="iso-record"><i/></div><section><b>{music.title||"Sunset"}</b><span>{music.artist||"IU"}</span><em><i style={{width:`${Math.max(30,music.progress)}%`}}/></em><small>1:36　　　　　　　　 -2:28</small><footer><button>◀</button><button onClick={music.togglePlay}>{music.playing?"Ⅱ":"▶"}</button><button onClick={()=>nav("/music")}>▶</button></footer></section></article>
 <article className="iso-card iso-tasks"><header><b>♣　오늘 할 일</b><span>{done}/{list.length||0}</span><button onClick={()=>nav("/today")}>＋</button></header><div>{list.map((x,i)=><button key={x.id} className={x.completed?"done":""} onClick={()=>toggle(x.id)}><i>{x.completed?"✓":""}</i><span>{x.title}</span><time>{x.time||`${10+i*2}:00`}</time></button>)}</div></article>
 <article className="iso-book" onClick={()=>nav("/notes")}><div><b>오늘의 한마디</b><p>“지금도 충분히 잘하고 있어.” ♡</p></div><i/><small>Good Day ♡</small></article>
 <article className="iso-card iso-calendar" onClick={()=>nav("/calendar")}><header>{now.getFullYear()}년 {now.getMonth()+1}월　　‹　›</header><div className="iso-week">{W.map(x=><b key={x}>{x}</b>)}</div><div className="iso-month">{Array.from({length:first}).map((_,i)=><i key={i}/>)}{Array.from({length:days},(_,i)=>i+1).map(d=><span className={d===now.getDate()?"today":""} key={d}>{d}</span>)}</div></article>
 <article className="iso-card iso-goals"><header>◎　이번 주 목표</header>{["규칙적인 생활하기","건강한 식습관","꾸준히 운동하기","기분 좋은 하루 만들기"].map(x=><button key={x}>○　{x}</button>)}</article>
 <footer className="iso-glass iso-dock">{[["◉","/"],["🌈","/gallery"],["▱","/notes"],["8","/calendar"],["♫","/music"],["◉","/"],["▰","/gallery"],["⚙","/settings"],["▦","/settings"]].map(([i,p],n)=><button key={n} onClick={()=>nav(p)}>{i}</button>)}</footer>
 </section>}
