import{useEffect,useMemo,useState}from"react";import{useNavigate}from"react-router-dom";import{useTaskStore}from"../../stores/taskStore";import{useWeatherStore}from"../../stores/weatherStore";import{useMusicStore}from"../../stores/musicStore";import{useFocusStore}from"../../stores/focusStore";import{localDateKey}from"../../utils/date";
const menu=[["⌂","Home","/"],["▦","Plan","/today"],["☑","Task","/today"],["▦","Calendar","/calendar"],["▤","Note","/notes"],["◎","Focus","/focus"],["♫","Music","/music"],["▧","Photo","/gallery"],["▥","Library","/notes"],["⚙","Setting","/settings"]];
export function LuxuryWatchHome(){const nav=useNavigate(),[now,setNow]=useState(new Date()),tasks=useTaskStore(s=>s.tasks),toggle=useTaskStore(s=>s.toggleTask),weather=useWeatherStore(s=>s.snapshot),load=useWeatherStore(s=>s.load),music=useMusicStore(),focus=useFocusStore();useEffect(()=>{const x=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(x)},[]);useEffect(()=>{load()},[load]);const key=localDateKey(now),list=useMemo(()=>tasks.filter(t=>t.date===key&&!t.deletedAt).slice(0,7),[tasks,key]),done=list.filter(t=>t.completed).length,first=new Date(now.getFullYear(),now.getMonth(),1).getDay(),days=new Date(now.getFullYear(),now.getMonth()+1,0).getDate();return <section className="luxury-home">
 <nav className="luxury-nav"><header>♛<b>MONDAILY</b><small>A<br/>BETTER<br/>YOU<br/>TODAY.</small></header>{menu.map(([i,n,p])=><button className={n==="Home"?"active":""} onClick={()=>nav(p)} key={n}><b>{i}</b>{n}</button>)}<footer>DISCIPLINE<br/>CREATES<br/>THE LIFE<br/>YOU WANT.</footer></nav>
 <article className="luxury-clock"><small>{now.toLocaleDateString("en-CA").replaceAll("-",". ")} · {now.toLocaleDateString("en-US",{weekday:"short"}).toUpperCase()} <span>SEOUL</span></small><strong>{now.toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"})}</strong><b>A BETTER ME TODAY.</b></article>
 <article className="luxury-weather" onClick={()=>load(true)}><i>☀</i><strong>{weather?.temperature??24}°C</strong><b>{weather?.description??"맑음"}</b><small>H:{weather?.high??26}°　L:{weather?.low??18}°</small><p>“오늘도, 좋은 하루가 될 거야.”</p></article>
 <article className="luxury-music"><div className="luxury-record"><i/></div><section><b>{music.title||"Golden Hour"}</b><span>{music.artist||"IU"}</span><em><i style={{width:`${Math.max(35,music.progress)}%`}}/></em><footer><button>◀</button><button onClick={music.togglePlay}>{music.playing?"Ⅱ":"▶"}</button><button onClick={()=>nav("/music")}>▶</button></footer></section><strong>♥</strong><p>Good Music.<br/>Better Day.</p></article>
 <article className="luxury-tasks"><header>TODAY'S TASK <span>{done}/{list.length}</span></header>{list.map(t=><button className={t.completed?"done":""} onClick={()=>toggle(t.id)} key={t.id}><i>{t.completed?"✓":""}</i>{t.title}</button>)}<footer>작은 습관이<br/>특별한 하루를 만든다.</footer></article>
 <article className="luxury-calendar" onClick={()=>nav("/calendar")}><header>‹　 {now.toLocaleDateString("en-US",{month:"long",year:"numeric"})}　 ›</header><div>{["일","월","화","수","목","금","토"].map(x=><b key={x}>{x}</b>)}{Array.from({length:first}).map((_,i)=><i key={i}/>)}{Array.from({length:days},(_,i)=>i+1).map(d=><span className={d===now.getDate()?"today":""} key={d}>{d}</span>)}</div><p>좋은 날이, 더 좋은 내가 되는 중. ♡</p></article>
 <article className="luxury-note" onClick={()=>nav("/notes")}><header>QUICK NOTE　•••</header><p>오늘도 수고했어.<br/>내일은 더 좋은 날이야. ♡</p><i>✒</i></article>
 <article className="luxury-apps"><header>QUICK APPS　•••</header>{[["▶","유튜브","/music"],["◎","인스타그램","/gallery"],["N","네이버","/"],["✉","메일","/notes"],["▲","드라이브","/gallery"],["◆","지도","/"],["◉","ChatGPT","/"],["＋","추가","/settings"]].map(([i,n,p])=><button key={n} onClick={()=>nav(p)}><b>{i}</b><span>{n}</span></button>)}</article>
 <article className="luxury-focus"><header>FOCUS TIMER　•••</header><strong>{focus.active?`${Math.floor(focus.remainingSeconds()/60)}:${String(focus.remainingSeconds()%60).padStart(2,"0")}`:"25:00"}</strong><button onClick={()=>focus.start(25,"Luxury Focus")}>▶</button><p>◎　Focus<br/>♨　Short Break<br/>☾　Long Break</p></article>
 <article className="luxury-gallery"><header>PHOTO GALLERY　•••</header>{["18% 55%","50% 58%","72% 64%","88% 60%"].map((p,i)=><button style={{backgroundPosition:p}} onClick={()=>nav("/gallery")} key={i}/>)}<p>MY FAVORITE MOMENTS. ♡</p></article>
 <article className="luxury-dday"><header>D-DAY　•••</header><p>✈　다음 여행 <span>D - 107</span><small>2026. 12. 24</small></p><p>▦　자격증 시험 <span>D - 39</span><small>2026. 10. 17</small></p><p>♥　소중한 날 <span>D - 56</span><small>2026. 11. 03</small></p></article>
 </section>}
