import{useEffect,useMemo,useState}from"react";import{useNavigate}from"react-router-dom";import{useFocusStore}from"../../stores/focusStore";import{useMusicStore}from"../../stores/musicStore";import{useTaskStore}from"../../stores/taskStore";import{useWeatherStore}from"../../stores/weatherStore";import{localDateKey}from"../../utils/date";const W=["일","월","화","수","목","금","토"];
export function MangaHome(){const nav=useNavigate(),[now,setNow]=useState(new Date()),tasks=useTaskStore(s=>s.tasks),toggle=useTaskStore(s=>s.toggleTask),weather=useWeatherStore(s=>s.snapshot),load=useWeatherStore(s=>s.load),music=useMusicStore(),focus=useFocusStore();useEffect(()=>{const i=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(i)},[]);useEffect(()=>{load()},[load]);const key=localDateKey(now),list=useMemo(()=>tasks.filter(x=>x.date===key&&!x.deletedAt).slice(0,7),[tasks,key]),done=list.filter(x=>x.completed).length,first=new Date(now.getFullYear(),now.getMonth(),1).getDay(),days=new Date(now.getFullYear(),now.getMonth()+1,0).getDate();return <section className="manga-home">
 <aside className="manga-side"><header>MY<br/>SPACE<small>Same day,<br/>Different me.</small></header><nav>{[["⌂","Home","/"],["☑","Todo","/today"],["▦","Calendar","/calendar"],["▤","Note","/notes"],["▧","Photo","/gallery"],["♫","Music","/music"],["◎","Web","/"],["■","File","/gallery"],["⚙","Setting","/settings"]].map(([i,n,p])=><button key={n} className={n==="Home"?"active":""} onClick={()=>nav(p)}><b>{i}</b>{n}</button>)}</nav><footer>Good<br/>Things<br/>Take<br/>Time. ☺</footer></aside>
 <article className="manga-scene"><strong>{now.toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"})}</strong><b>{now.toLocaleDateString("ko-KR",{month:"long",day:"numeric",weekday:"long"})}</b><p>오늘도<br/>나답게,<br/>조금 더 멋지게. ♡</p><div className="manga-person"><i/><span>◉</span></div><div className="manga-cat">▲　▲<br/>●ᴥ●</div><small>A Brighter<br/>You<br/>Today. ♡</small></article>
 <article className="manga-panel manga-weather" onClick={()=>load(true)}><div><i>🌤️</i><section><span>SEOUL</span><strong>{weather?.temperature??24}°</strong><b>{weather?.description??"맑음"}</b><small>H:{weather?.high??26}°　L:{weather?.low??18}°</small></section></div><div className="manga-city"/></article>
 <article className="manga-panel manga-music"><div className="manga-record"/><section><b>{music.title||"Good Days"}</b><span>{music.artist||"IU"}</span><em><i style={{width:`${Math.max(28,music.progress)}%`}}/></em><small>1:27　　　　　　　　 -2:18</small><footer><button>◀</button><button onClick={music.togglePlay}>{music.playing?"Ⅱ":"▶"}</button><button onClick={()=>nav("/music")}>▶</button></footer><p>“좋은 음악이<br/>오늘을 더 특별하게.”</p></section></article>
 <article className="manga-panel manga-tasks"><header><b>TODAY</b><span>{done}/{list.length||0}</span></header><div>{list.map(x=><button key={x.id} className={x.completed?"done":""} onClick={()=>toggle(x.id)}><i>{x.completed?"✓":""}</i>{x.title}</button>)}</div><small>Do<br/>It<br/>For<br/>a Better<br/>You ♡</small></article>
 <article className="manga-panel manga-calendar" onClick={()=>nav("/calendar")}><header>‹　　{now.getFullYear()}. {now.getMonth()+1}　　›</header><div className="manga-week">{W.map(x=><b key={x}>{x}</b>)}</div><div className="manga-month">{Array.from({length:first}).map((_,i)=><i key={i}/>)}{Array.from({length:days},(_,i)=>i+1).map(d=><span className={d===now.getDate()?"today":""} key={d}>{d}</span>)}</div><footer>Every day is a new page. ♡</footer></article>
 <aside className="manga-panel manga-quote">“ 지금도 충분히 잘하고 있어.”<small>You’re doing better than you think.</small><b>❀</b></aside>
 <article className="manga-panel manga-apps"><header>Quick Apps</header><div>{[["▶","유튜브","/music"],["◎","인스타그램","/gallery"],["N","네이버","/"],["◆","지도","/"],["✉","메일","/notes"],["▲","드라이브","/gallery"],["G文","번역","/"],["◉","ChatGPT","/"]].map(([i,n,p])=><button key={n} onClick={()=>nav(p)}><b>{i}</b><span>{n}</span></button>)}</div></article>
 <article className="manga-gallery" onClick={()=>nav("/gallery")}><header>My<br/>Gallery<small>Collect<br/>Beautiful<br/>Moments. ♡</small></header><div>{[1,2,3,4].map(x=><i key={x}/>)}</div></article>
 <aside className="manga-night">☾<small>Same sky,<br/>Different you.</small></aside>
 <article className="manga-panel manga-focus"><header>Focus Timer</header><div><span><b>{focus.active?`${Math.floor(focus.remainingSeconds()/60)}:${String(focus.remainingSeconds()%60).padStart(2,"0")}`:"25:00"}</b></span><section><button onClick={()=>focus.start(25,"Manga Focus")}>◎　Focus</button><button onClick={()=>focus.start(5,"Short Break")}>♨　Short Break</button><button onClick={()=>focus.start(15,"Long Break")}>☾　Long Break</button></section></div></article>
 </section>}
