import{useEffect,useMemo,useState}from"react";import{useNavigate}from"react-router-dom";import{useTaskStore}from"../../stores/taskStore";import{useWeatherStore}from"../../stores/weatherStore";import{useMusicStore}from"../../stores/musicStore";import{useFocusStore}from"../../stores/focusStore";import{localDateKey}from"../../utils/date";
const menu=[["⌂","Home","/"],["▦","Plan","/today"],["☑","Task","/today"],["▦","Calendar","/calendar"],["▤","Note","/notes"],["◎","Focus","/focus"],["♫","Music","/music"],["▧","Photo","/gallery"],["▥","Library","/notes"],["●","Map","/"],["▣","Archive","/gallery"],["⚙","Setting","/settings"]];
export function MedicalHome(){const nav=useNavigate(),[now,setNow]=useState(new Date()),tasks=useTaskStore(s=>s.tasks),toggle=useTaskStore(s=>s.toggleTask),weather=useWeatherStore(s=>s.snapshot),load=useWeatherStore(s=>s.load),music=useMusicStore(),focus=useFocusStore();useEffect(()=>{const x=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(x)},[]);useEffect(()=>{load()},[load]);const key=localDateKey(now),list=useMemo(()=>tasks.filter(t=>t.date===key&&!t.deletedAt).slice(0,7),[tasks,key]),done=list.filter(t=>t.completed).length,first=new Date(now.getFullYear(),now.getMonth(),1).getDay(),days=new Date(now.getFullYear(),now.getMonth()+1,0).getDate();return <section className="medical-home">
 <nav className="medical-nav"><header><i>⌁</i>A<br/>HEALTHIER<br/>YOU<br/>TODAY.</header>{menu.map(([i,n,p])=><button className={n==="Home"?"active":""} onClick={()=>nav(p)} key={n}><b>{i}</b>{n}</button>)}<footer>SMALL<br/>HABITS<br/>BRING<br/>BIG<br/>CHANGES. ＋</footer></nav>
 <aside className="medical-anatomy"><header>HUMAN<br/>ANATOMY</header><div/><small>BETTER BODY<br/>BETTER MIND</small></aside>
 <article className="medical-clock"><small>{now.toLocaleDateString("en-CA").replaceAll("-",". ")} · {now.toLocaleDateString("en-US",{weekday:"short"}).toUpperCase()}</small><strong>{now.toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"})}</strong><p>지금도 충분히 잘하고 있어. ♡</p><b>HEALTHY MIND. HEALTHY LIFE.</b><i>⌁</i></article>
 <article className="medical-body"><header>BODY STATUS</header><div/><section><p>♥ <b>72</b><small>bpm</small></p><p>♨ <b>36.5</b><small>°C</small></p><p>◉ <b>98</b><small>SpO₂</small></p></section><footer>BETTER TODAY<br/>THAN YESTERDAY.</footer></article>
 <article className="medical-music"><div className="medical-record"><i/></div><section><b>{music.title||"Healing Moment"}</b><span>{music.artist||"IU"}</span><em><i style={{width:`${Math.max(35,music.progress)}%`}}/></em><footer><button>◀</button><button onClick={music.togglePlay}>{music.playing?"Ⅱ":"▶"}</button><button onClick={()=>nav("/music")}>▶</button></footer></section><strong>♥</strong><p>Music for<br/>a better you.</p></article>
 <article className="medical-tasks"><header>Today's Task <span>{done}/{list.length}</span></header>{list.map(t=><button className={t.completed?"done":""} onClick={()=>toggle(t.id)} key={t.id}><i>{t.completed?"✓":""}</i>{t.title}</button>)}<footer>작은 습관이<br/>특별한 하루를 만든다. ♡</footer></article>
 <article className="medical-calendar" onClick={()=>nav("/calendar")}><header>‹　 {now.toLocaleDateString("en-US",{month:"long",year:"numeric"})}　 ›</header><div>{["일","월","화","수","목","금","토"].map(x=><b key={x}>{x}</b>)}{Array.from({length:first}).map((_,i)=><i key={i}/>)}{Array.from({length:days},(_,i)=>i+1).map(d=><span className={d===now.getDate()?"today":""} key={d}>{d}</span>)}</div><p>조금씩, 더 좋은 내가 되는 중. ♡</p></article>
 <article className="medical-note" onClick={()=>nav("/notes")}><header>Quick Note</header><div><b>오늘도<br/>수고했어.<br/>내일은 더 좋은 날이야. ♡</b></div><aside>Good<br/>Only ♡</aside></article>
 <article className="medical-apps"><header>Quick Apps　•••</header>{[["▶","유튜브","/music"],["◎","인스타그램","/gallery"],["N","네이버","/"],["✉","메일","/notes"],["▲","드라이브","/gallery"],["◆","지도","/"],["◉","ChatGPT","/"],["＋","추가","/settings"]].map(([i,n,p])=><button key={n} onClick={()=>nav(p)}><b>{i}</b><span>{n}</span></button>)}</article>
 <article className="medical-focus"><header>Focus Timer　•••</header><strong>{focus.active?`${Math.floor(focus.remainingSeconds()/60)}:${String(focus.remainingSeconds()%60).padStart(2,"0")}`:"25:00"}</strong><button onClick={()=>focus.start(25,"Medical Focus")}>▶</button><p>◎　Focus<br/>♨　Short Break<br/>☾　Long Break</p></article>
 <article className="medical-gallery"><header>Medical Gallery　•••</header>{["20% 70%","50% 65%","78% 68%"].map((p,i)=><button style={{backgroundPosition:p}} onClick={()=>nav("/gallery")} key={i}/>)}<p>Take Care of Yourself. ♡</p></article>
 <article className="medical-dday"><header>D-Day　•••</header><p>✈　다음 여행 <span>D - 107</span><small>2026. 12. 24</small></p><p>▦　자격증 시험 <span>D - 39</span><small>2026. 10. 17</small></p><p>♥　소중한 날 <span>D - 56</span><small>2026. 11. 03</small></p></article>
 </section>}
