import{useEffect,useMemo,useState}from"react";import{useNavigate}from"react-router-dom";import{useMusicStore}from"../../stores/musicStore";import{useTaskStore}from"../../stores/taskStore";import{useWeatherStore}from"../../stores/weatherStore";import{localDateKey}from"../../utils/date";
const W=["일","월","화","수","목","금","토"];
export function MinimalGalleryHome(){const nav=useNavigate(),[now,setNow]=useState(new Date()),tasks=useTaskStore(s=>s.tasks),toggle=useTaskStore(s=>s.toggleTask),weather=useWeatherStore(s=>s.snapshot),load=useWeatherStore(s=>s.load),music=useMusicStore();useEffect(()=>{const i=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(i)},[]);useEffect(()=>{load()},[load]);const key=localDateKey(now),list=useMemo(()=>tasks.filter(x=>x.date===key&&!x.deletedAt).slice(0,7),[tasks,key]),done=list.filter(x=>x.completed).length,first=new Date(now.getFullYear(),now.getMonth(),1).getDay(),days=new Date(now.getFullYear(),now.getMonth()+1,0).getDate();return <section className="mg-home">
 <div className="mg-room"><div className="mg-arch"><i/><span>A<br/><em>Better</em><br/>Me<small>Same Day<br/>A Brighter Tomorrow.</small></span></div><div className="mg-bench"><i/><i/><b>The Daily<br/>A Better Me</b></div><div className="mg-pool"/></div>
 <aside className="mg-side"><small>A<br/>SLOWER DAY<br/>A BRIGHTER<br/>YOU</small><strong>{now.toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"})}</strong><b>{now.toLocaleDateString("ko-KR",{month:"long",day:"numeric",weekday:"long"})}</b><p>지금도<br/>충분히 잘하고 있어.<br/>오늘도<br/>좋은 하루가 될 거야. ♡</p><nav>{[["⌂","Home","/"],["▣","Plan","/calendar"],["◒","Focus","/focus"],["▤","Note","/notes"],["▥","Habit","/today"],["▧","Gallery","/gallery"],["⚙","Settings","/settings"]].map(([i,n,p])=><button key={n} className={n==="Home"?"active":""} onClick={()=>nav(p)}><b>{i}</b>{n}</button>)}</nav></aside>
 <article className="mg-card mg-weather" onClick={()=>load(true)}><header>{weather?.locationLabel||"인천광역시"}</header><div><i>☀</i><section><b>{weather?.description||"맑음"}</b><strong>{weather?.temperature??26}°</strong><small>체감 {weather?.apparentTemperature??27}°</small></section><p>좋은 일이<br/>오늘도<br/>네 곁에 있기를. ♡</p></div><footer>{[["지금","☀","26°"],["12시","☀","28°"],["15시","🌤","27°"],["18시","☁","25°"],["21시","☾","23°"]].map(x=><span key={x[0]}>{x[0]}<b>{x[1]}</b><small>{x[2]}</small></span>)}</footer></article>
 <aside className="mg-art">Focus<br/>On<br/>What<br/>Matters.<i/></aside>
 <article className="mg-card mg-tasks"><header><b>오늘 할 일</b><span>{done}/{list.length||0}</span><button onClick={()=>nav("/today")}>＋</button></header><div>{list.map((x,i)=><button key={x.id} className={x.completed?"done":""} onClick={()=>toggle(x.id)}><i>{x.completed?"✓":""}</i><span>{x.title}</span><time>{x.time||`${10+i*2}:00`}</time></button>)}</div></article>
 <article className="mg-card mg-music"><div className="mg-record"><i/></div><section><b>{music.title||"Daylight"}</b><span>{music.artist||"IU"}</span><p>좋은 날이 올 거야.</p><em><i style={{width:`${Math.max(30,music.progress)}%`}}/></em><small>1:18　　　　　　　　 -3:02</small><footer><button>⤨</button><button>◀</button><button onClick={music.togglePlay}>{music.playing?"Ⅱ":"▶"}</button><button onClick={()=>nav("/music")}>▶</button><button>♥</button></footer></section></article>
 <article className="mg-card mg-calendar" onClick={()=>nav("/calendar")}><header>{now.getFullYear()}년 {now.getMonth()+1}월　　‹　›</header><div className="mg-week">{W.map(x=><b key={x}>{x}</b>)}</div><div className="mg-month">{Array.from({length:first}).map((_,i)=><i key={i}/>)}{Array.from({length:days},(_,i)=>i+1).map(d=><span className={d===now.getDate()?"today":""} key={d}>{d}</span>)}</div></article>
 <aside className="mg-card mg-quote">“<p>오늘도,<br/>수고했어.</p><small>Small Steps<br/>Make A Big Change.</small><i/></aside>
 <footer className="mg-dock">{[["◉","/"],["🌈","/gallery"],["▱","/notes"],["8","/calendar"],["♫","/music"],["◉","/"],["▰","/gallery"],["⚙","/settings"],["▦","/settings"]].map(([i,p],n)=><button key={n} onClick={()=>nav(p)}>{i}</button>)}</footer>
 </section>}
