import{useEffect,useMemo,useState}from"react";import{useNavigate}from"react-router-dom";import{useTaskStore}from"../../stores/taskStore";import{useWeatherStore}from"../../stores/weatherStore";import{useMusicStore}from"../../stores/musicStore";import{useScheduleStore}from"../../stores/scheduleStore";import{useFocusStore}from"../../stores/focusStore";import{localDateKey}from"../../utils/date";
export function ModularSynthHome(){const nav=useNavigate(),[now,setNow]=useState(new Date()),tasks=useTaskStore(s=>s.tasks),toggle=useTaskStore(s=>s.toggleTask),weather=useWeatherStore(s=>s.snapshot),load=useWeatherStore(s=>s.load),music=useMusicStore(),schedules=useScheduleStore(s=>s.schedules),focus=useFocusStore();useEffect(()=>{const x=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(x)},[]);useEffect(()=>{load()},[load]);const key=localDateKey(now),list=useMemo(()=>tasks.filter(t=>t.date===key&&!t.deletedAt).slice(0,5),[tasks,key]),plans=useMemo(()=>schedules.filter(s=>s.date===key&&!s.deletedAt).slice(0,6),[schedules,key]);return <section className="synth-home">
 <div className="synth-chassis"><i/><i/><i/><i/></div>
 <article className="synth-clock"><small>{now.toLocaleDateString("en-CA").replaceAll("-",". ")} ({now.toLocaleDateString("ko-KR",{weekday:"short"})})</small><strong>{now.toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"})}</strong><b>GOOD SOUND.<br/>BETTER DAY.</b></article>
 <article className="synth-weather" onClick={()=>load(true)}><header>서울특별시</header><i>🌤</i><strong>{weather?.temperature??18}°</strong><b>{weather?.description??"구름 조금"}</b><small>최고 {weather?.high??22}°　최저 {weather?.low??11}°</small></article>
 <article className="synth-scene"><div/><p>RHYTHM<br/>MAKES<br/>A BRIGHTER<br/>TOMORROW.</p></article>
 <article className="synth-wave"><header>INDUSTRIAL<br/>SYNTH BOARD</header><div>{Array.from({length:36},(_,i)=><i style={{height:`${20+((i*17)%55)}%`}} key={i}/>)}</div><small>SOUNDING<br/>A MORE PRODUCTIVE<br/>TOMORROW.</small></article>
 <article className="synth-tasks"><header>오늘의 할 일 <span>{list.length}　＋</span></header>{list.map(t=><button onClick={()=>toggle(t.id)} className={t.completed?"done":""} key={t.id}><i>{t.completed?"✓":""}</i>{t.title}</button>)}</article>
 <article className="synth-player"><div className="synth-art"/><section><b>{music.title||"Higher Ground"}</b><span>{music.artist||"ODESZA"}</span><em><i style={{width:`${Math.max(35,music.progress)}%`}}/></em><footer><button>⌘</button><button>◀</button><button onClick={music.togglePlay}>{music.playing?"Ⅱ":"▶"}</button><button onClick={()=>nav("/music")}>▶</button></footer></section><strong>♡</strong></article>
 <article className="synth-mixer"><header>SOUND IS<br/>PRODUCTIVITY.</header><div className="synth-bars">{Array.from({length:45},(_,i)=><i className={i%3===0?"orange":"cyan"} style={{height:`${16+((i*23)%75)}%`}} key={i}/>)}</div><nav><button className="active">MUSIC</button><button onClick={()=>nav("/focus")}>FOCUS</button><button>AMBIENT</button></nav><section>{["LOW","MID","HIGH","MASTER"].map((n,i)=><span className={i===3?"master":""} key={n}><i/><b>{n}</b></span>)}</section><aside>{Array.from({length:15},(_,i)=><i style={{height:`${8+i*5}%`}} key={i}/>)}</aside></article>
 <article className="synth-memo" onClick={()=>nav("/notes")}><header>빠른 메모　＋</header><p>좋은 사운드가<br/>좋은 하루를 만든다.<br/><br/>Same Vibes,<br/>Higher Work.</p></article>
 <article className="synth-schedule" onClick={()=>nav("/calendar")}><header>오늘의 일정　＋</header>{(plans.length?plans:[["09:00","기획 회의"],["11:00","클라이언트 미팅"],["13:00","점심 식사"],["15:00","프로토타입 리뷰"],["18:00","운동"],["20:00","저녁 약속"]]).map((p:any,i)=><p key={p.id||i}><i/>{p.startTime||p[0]}　 {p.title||p[1]}</p>)}</article>
 <article className="synth-progress"><div/><p>SMALL<br/>STEPS.<br/>BIG<br/>PROGRESS.</p><small>▥▥▥▥▥▥▥▥▥▥<br/>A BETTER YOU<br/>SOUNDS GOOD.</small></article>
 <nav className="synth-tools">{[["♫","MUSIC","/music"],["◉","FOCUS","/focus"],["▰","FILES","/gallery"],["◈","BROWSER","/"],["⚙","SETTING","/settings"]].map(([i,n,p])=><button onClick={()=>nav(p)} key={n}><b>{i}</b><span>{n}</span></button>)}</nav>
 <button className="synth-focus" onClick={()=>focus.start(25,"Synth Focus")}>{focus.active?`${Math.floor(focus.remainingSeconds()/60)}:${String(focus.remainingSeconds()%60).padStart(2,"0")}`:"25:00"}</button>
 </section>}
