import{useEffect,useMemo,useState}from"react";import{useNavigate}from"react-router-dom";import{useTaskStore}from"../../stores/taskStore";import{useWeatherStore}from"../../stores/weatherStore";import{useMusicStore}from"../../stores/musicStore";import{useFocusStore}from"../../stores/focusStore";import{localDateKey}from"../../utils/date";
const menu=[["⌂","Home","/"],["☑","Today","/today"],["▦","Calendar","/calendar"],["☑","Task","/today"],["▤","Note","/notes"],["▧","Photo","/gallery"],["♫","Music","/music"],["▤","News","/today"],["☀","Weather","/"],["▣","Archive","/gallery"],["⚙","Setting","/settings"]];
export function NewspaperHome(){const nav=useNavigate(),[now,setNow]=useState(new Date()),tasks=useTaskStore(s=>s.tasks),toggle=useTaskStore(s=>s.toggleTask),weather=useWeatherStore(s=>s.snapshot),load=useWeatherStore(s=>s.load),music=useMusicStore(),focus=useFocusStore();useEffect(()=>{const x=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(x)},[]);useEffect(()=>{load()},[load]);const list=useMemo(()=>tasks.filter(t=>t.date===localDateKey(now)&&!t.deletedAt).slice(0,7),[tasks,now]),done=list.filter(t=>t.completed).length;return <section className="news-home">
 <header className="news-mast"><small>A<br/>Brighter<br/>You<br/>Today.</small><h1>The Daily Chronicle</h1><b>VOL. 1　NO. 238<br/>{now.toLocaleDateString("en-US",{weekday:"long",month:"short",day:"numeric",year:"numeric"})}</b><i>Same day.<br/>Different me.</i><footer>GOOD HABITS MAKE A BRIGHTER TOMORROW.</footer></header>
 <nav className="news-nav">{menu.map(([i,n,p])=><button className={n==="Home"?"active":""} onClick={()=>nav(p)} key={n}><b>{i}</b>{n}</button>)}</nav>
 <article className="news-hero"><div/><p>오늘도<br/>조금 더<br/>좋아질 거야. ♡</p><b>Small Steps,<br/>Big Changes.</b><footer>SEOUL, {now.toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"})}<span>SAME VIEW.<br/>DIFFERENT YOU.</span></footer></article>
 <article className="news-clock"><header>{now.toLocaleDateString("en-US",{weekday:"long"})}<span>{now.toLocaleDateString("en-CA").replaceAll("-",". ")}</span></header><strong>{now.toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"})}</strong><p>“ 지금도 충분히 잘하고 있어. ”</p><small>A BRIGHTER YOU TODAY.</small></article>
 <article className="news-weather" onClick={()=>load(true)}><header>SEOUL　›</header><i>☀</i><strong>{weather?.temperature??24}°C</strong><b>{weather?.description??"맑음"}</b><small>H:{weather?.high??26}°　L:{weather?.low??18}°</small><div/></article>
 <article className="news-music"><header>MUSIC FOR TODAY　♥</header><div className="news-record"/><section><b>{music.title||"Nice Day"}</b><span>{music.artist||"IU"}</span><em><i style={{width:`${Math.max(35,music.progress)}%`}}/></em><footer><button>◀</button><button onClick={music.togglePlay}>{music.playing?"Ⅱ":"▶"}</button><button onClick={()=>nav("/music")}>▶</button></footer></section><small>GOOD MUSIC<br/>BETTER DAYS.</small></article>
 <article className="news-tasks"><header>TODAY'S CHECKLIST <span>{done}/{list.length}</span></header>{list.map(t=><button className={t.completed?"done":""} onClick={()=>toggle(t.id)} key={t.id}><i>{t.completed?"✓":""}</i>{t.title}</button>)}<small>DO A LITTLE MORE<br/>FOR A BETTER TOMORROW.</small></article>
 <article className="news-calendar" onClick={()=>nav("/calendar")}><header>‹　 {now.toLocaleDateString("en-US",{month:"long",year:"numeric"})}　 ›</header><div>{["일","월","화","수","목","금","토"].map(x=><b key={x}>{x}</b>)}{Array.from({length:new Date(now.getFullYear(),now.getMonth(),1).getDay()}).map((_,i)=><i key={i}/>)}{Array.from({length:new Date(now.getFullYear(),now.getMonth()+1,0).getDate()},(_,i)=>i+1).map(d=><span className={d===now.getDate()?"today":""} key={d}>{d}</span>)}</div><p>좋은 날이 더 많기를. ♡</p></article>
 <article className="news-quote"><header>DAILY QUOTE</header><div/><p>지금도 충분히<br/>잘하고 있어.</p><small>A BRIGHTER<br/>YOU TODAY.</small></article>
 <aside className="news-sidequote">“<br/><p>A calmer mind<br/>creates<br/>a brighter day.</p>”</aside>
 <article className="news-story"><header>TOP NEWS <span>MORE ›</span></header><div/><h2>A More<br/>Productive Day<br/>Starts with<br/>A Clear Mind.</h2><p>작은 습관이<br/>특별한 하루를 만든다.<br/>오늘도, 조금 더.</p></article>
 <article className="news-apps"><header>QUICK APPS</header>{[["▶","유튜브","/music"],["◎","인스타그램","/gallery"],["N","네이버","/"],["✉","메일","/notes"],["▲","드라이브","/gallery"],["◆","지도","/"],["＋","추가","/settings"]].map(([i,n,p])=><button key={n} onClick={()=>nav(p)}><b>{i}</b><span>{n}</span></button>)}</article>
 <article className="news-focus"><header>FOCUS TIMER</header><strong>{focus.active?`${Math.floor(focus.remainingSeconds()/60)}:${String(focus.remainingSeconds()%60).padStart(2,"0")}`:"25:00"}</strong><button onClick={()=>focus.start(25,"Editorial Focus")}>▶</button><p>◎　Focus<br/>♨　Short Break<br/>☾　Long Break</p></article>
 <article className="news-memo"><header>TODAY'S MEMO　•••</header><p>오늘도 수고했어.<br/>내일은 더 좋은 날이야. ♡</p><small>WRITE A BETTER TOMORROW.</small></article>
 </section>}
