import{useEffect,useMemo,useState}from"react";import{useNavigate}from"react-router-dom";import{useTaskStore}from"../../stores/taskStore";import{useWeatherStore}from"../../stores/weatherStore";import{useMusicStore}from"../../stores/musicStore";import{useFocusStore}from"../../stores/focusStore";import{localDateKey}from"../../utils/date";
const navs=[["⌂","Home","/"],["⚑","Plan","/today"],["▦","Calendar","/calendar"],["☑","Task","/today"],["▤","Note","/notes"],["♫","Music","/music"],["▧","Photo","/gallery"],["●","Map","/"],["◆","Car","/focus"],["⚙","Setting","/settings"]];
export function RacingHome(){const nav=useNavigate(),[now,setNow]=useState(new Date()),tasks=useTaskStore(s=>s.tasks),toggle=useTaskStore(s=>s.toggleTask),weather=useWeatherStore(s=>s.snapshot),load=useWeatherStore(s=>s.load),music=useMusicStore(),focus=useFocusStore();useEffect(()=>{const x=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(x)},[]);useEffect(()=>{load()},[load]);const list=useMemo(()=>tasks.filter(t=>t.date===localDateKey(now)&&!t.deletedAt).slice(0,7),[tasks,now]),done=list.filter(t=>t.completed).length;return <section className="race-home">
 <nav className="race-nav"><p>DRIVE<br/>YOUR<br/>DAY.</p>{navs.map(([i,n,p])=><button className={n==="Home"?"active":""} onClick={()=>nav(p)} key={n}><b>{i}</b>{n}</button>)}<small>SAME ROUTE.<br/>DIFFERENT STORIES.</small></nav>
 <article className="race-clock"><small>A BETTER<br/>YOU<br/>A FASTER<br/>TOMORROW.</small><strong>{now.toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"})}</strong><b>{now.toLocaleDateString("ko-KR",{month:"long",day:"numeric",weekday:"long"})}</b></article>
 <article className="race-weather" onClick={()=>load(true)}><span>SEOUL</span><i>☾</i><strong>{weather?.temperature??24}°C</strong><b>{weather?.description??"맑음"}</b><small>H:{weather?.high??26}° L:{weather?.low??18}°</small></article>
 <article className="race-music"><div className="race-cover"/><section><b>{music.title||"On The Road"}</b><span>{music.artist||"Lany"}</span><em><i style={{width:`${Math.max(38,music.progress)}%`}}/></em><footer><button>◀</button><button onClick={music.togglePlay}>{music.playing?"Ⅱ":"▶"}</button><button onClick={()=>nav("/music")}>▶</button></footer></section><strong>♥</strong></article>
 <article className="race-tasks"><header>TODAY'S PIT STOP <span>{done}/{list.length}</span></header>{list.map(t=><button className={t.completed?"done":""} onClick={()=>toggle(t.id)} key={t.id}><i>{t.completed?"✓":""}</i>{t.title}</button>)}<small>SMALL STEPS<br/>MAKE A BIG LAP.　⚑</small></article>
 <article className="race-calendar" onClick={()=>nav("/calendar")}><header>‹　 {now.getFullYear()}. {now.getMonth()+1}　 ›</header><div>{["일","월","화","수","목","금","토"].map(x=><b key={x}>{x}</b>)}{Array.from({length:new Date(now.getFullYear(),now.getMonth(),1).getDay()}).map((_,i)=><i key={i}/>)}{Array.from({length:new Date(now.getFullYear(),now.getMonth()+1,0).getDate()},(_,i)=>i+1).map(d=><span className={d===now.getDate()?"today":""} key={d}>{d}</span>)}</div></article>
 <article className="race-stats"><header>FUEL<br/>YOUR<br/>PASSION.</header><div className="race-track">⌁</div>{[["FOCUS",85],["HEALTH",70],["STUDY",60],["LIFE",90]].map(([n,v])=><p key={n}><span>{n}</span><i><b style={{width:`${v}%`}}/></i><strong>{v}%</strong></p>)}</article>
 <article className="race-apps"><header>QUICK APPS</header>{[["▶","유튜브","/music"],["◎","인스타그램","/gallery"],["N","네이버","/"],["✉","메일","/notes"],["◆","지도","/"],["●","스포티파이","/music"],["＋","추가","/settings"]].map(([i,n,p])=><button key={n} onClick={()=>nav(p)}><b>{i}</b><span>{n}</span></button>)}</article>
 <aside className="race-note">지금도<br/>충분히 잘하고 있어.<br/>오늘도 조금 더<br/>나아갈 거야. ♡</aside>
 <article className="race-focus"><header>FOCUS TIMER</header><strong>{focus.active?`${Math.floor(focus.remainingSeconds()/60)}:${String(focus.remainingSeconds()%60).padStart(2,"0")}`:"25:00"}</strong><button onClick={()=>focus.start(25,"Drive Focus")}>▶</button><p>◎　Focus<br/>▱　Short Break<br/>☾　Long Break</p></article>
 </section>}
