import{useEffect,useMemo,useState}from"react";import{useNavigate}from"react-router-dom";import{useFocusStore}from"../../stores/focusStore";import{useMusicStore}from"../../stores/musicStore";import{useScheduleStore}from"../../stores/scheduleStore";import{useTaskStore}from"../../stores/taskStore";import{useWeatherStore}from"../../stores/weatherStore";import{localDateKey}from"../../utils/date";
const W=["일","월","화","수","목","금","토"];
export function RetroPixelHome(){const nav=useNavigate(),[now,setNow]=useState(new Date()),tasks=useTaskStore(s=>s.tasks),toggle=useTaskStore(s=>s.toggleTask),events=useScheduleStore(s=>s.schedules),weather=useWeatherStore(s=>s.snapshot),load=useWeatherStore(s=>s.load),music=useMusicStore(),focus=useFocusStore();useEffect(()=>{const i=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(i)},[]);useEffect(()=>{load()},[load]);const key=localDateKey(now),list=useMemo(()=>tasks.filter(x=>x.date===key&&!x.deletedAt).slice(0,7),[tasks,key]),done=list.filter(x=>x.completed).length,schedule=events.filter(x=>x.date===key&&!x.deletedAt).sort((a,b)=>a.startTime.localeCompare(b.startTime)).slice(0,4),first=new Date(now.getFullYear(),now.getMonth(),1).getDay(),days=new Date(now.getFullYear(),now.getMonth()+1,0).getDate();return <section className="rp-home">
 <div className="rp-room"><div className="rp-sky"><i/><i/><i/><i/><span>오늘도<br/>좋은 하루 ♡<small>GOOD DAYS<br/>BLOOM HERE.</small></span></div><div className="rp-desk"><i/><b>⌒•ᴥ•⌒</b></div></div>
 <aside className="rp-side"><small>GOOD<br/>THINGS<br/>TAKE TIME</small><nav>{[["⌂","Home","/"],["▣","Planner","/calendar"],["◷","Focus","/focus"],["▧","Gallery","/gallery"],["▤","Memo","/notes"],["⚙","Settings","/settings"]].map(([i,n,p])=><button key={n} className={n==="Home"?"active":""} onClick={()=>nav(p)}><b>{i}</b>{n}</button>)}</nav><footer>A<br/>SLOWER<br/>BRIGHTER<br/>TOMORROW</footer></aside>
 <article className="rp-clock"><small>Have a<br/>Good Day!</small><strong>{now.toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"})}</strong><b>{now.toLocaleDateString("ko-KR",{month:"long",day:"numeric",weekday:"long"})}</b><p>지금도 충분히 잘하고 있어.<br/>오늘도, 좋은 하루가 될 거야. ♡</p><em>A BRIGHTER<br/>TOMORROW</em></article>
 <article className="rp-glass rp-weather" onClick={()=>load(true)}><header>{weather?.locationLabel||"서울특별시"}</header><div><i>🌤️</i><section><b>{weather?.description||"맑음"}</b><strong>{weather?.temperature??23}°</strong><small>체감 {weather?.apparentTemperature??22}°</small></section><p>좋은 일은<br/>언제나<br/>네 곁에 있어. ♡</p></div><footer>{[["지금","☀","23°"],["12시","☀","25°"],["15시","🌤","24°"],["18시","☁","22°"],["21시","☾","20°"]].map(x=><span key={x[0]}>{x[0]}<b>{x[1]}</b><small>{x[2]}</small></span>)}</footer></article>
 <article className="rp-glass rp-music"><header>● Music for a Better You　•••</header><div className="rp-album"/><section><b>{music.title||"Sunset Drive"}</b><span>{music.artist||"IU"}</span><p>“조금 더<br/>행복해질 거야.”</p><em><i style={{width:`${Math.max(31,music.progress)}%`}}/></em><small>1:42　　　　　　　　　-2:18</small><footer><button>⤨</button><button>◀</button><button onClick={music.togglePlay}>{music.playing?"Ⅱ":"▶"}</button><button onClick={()=>nav("/music")}>▶</button><button>♥</button></footer></section></article>
 <article className="rp-glass rp-tasks"><header><b>▰　오늘 할 일</b><span>{done}/{list.length||0}</span><button onClick={()=>nav("/today")}>＋</button></header><div>{list.map((x,i)=><button key={x.id} className={x.completed?"done":""} onClick={()=>toggle(x.id)}><i>{x.completed?"✓":""}</i><span>{x.title}</span><time>{x.time||`${10+i*2}:00`}</time></button>)}</div></article>
 <article className="rp-glass rp-plan"><header>▣　오늘의 일정 <button onClick={()=>nav("/calendar")}>＋</button></header><div>{schedule.length?schedule.map((x,i)=><p key={x.id}><time>{x.startTime}</time><i className={`c${i}`}/><span>{x.title}</span></p>):<p><time>--:--</time><i/><span>등록된 일정 없음</span></p>}</div><h3>{now.getFullYear()}년 {now.getMonth()+1}월</h3><div className="rp-week">{W.map(x=><b key={x}>{x}</b>)}</div><div className="rp-month">{Array.from({length:first}).map((_,i)=><i key={i}/>)}{Array.from({length:days},(_,i)=>i+1).map(d=><span className={d===now.getDate()?"today":""} key={d}>{d}</span>)}</div></article>
 <aside className="rp-glass rp-words">좋아하는 것들로<br/>가득한 하루가<br/>더 좋은 하루를 만든다. ♡<small>FILL<br/>YOUR DAY<br/>WITH<br/>HAPPINESS.</small></aside>
 <footer className="rp-glass rp-dock">{[["◉","Safari","/"],["🌈","사진","/gallery"],["▱","메모","/notes"],["8","캘린더","/calendar"],["♫","Music","/music"],["◉","ChatGPT","/"],["▰","파일","/gallery"],["⚙","설정","/settings"]].map(([i,n,p])=><button key={n} onClick={()=>nav(p)}><b>{i}</b><span>{n}</span></button>)}</footer>
 <button className="rp-glass rp-focus" onClick={()=>focus.active?nav("/focus"):focus.start(25,"Soft Focus")}><i>∞</i><span>Focus<strong>{focus.active?`${Math.floor(focus.remainingSeconds()/60)}:${String(focus.remainingSeconds()%60).padStart(2,"0")}`:"25:00"}</strong><small>지금, 더 좋은 내가 되는 시간</small></span><b>▶</b></button>
 </section>}
