import{useEffect,useMemo,useState}from"react";import{useNavigate}from"react-router-dom";import{useFocusStore}from"../../stores/focusStore";import{useMusicStore}from"../../stores/musicStore";import{useTaskStore}from"../../stores/taskStore";import{useWeatherStore}from"../../stores/weatherStore";import{localDateKey}from"../../utils/date";const W=["일","월","화","수","목","금","토"];
export function ScientificLabHome(){const nav=useNavigate(),[now,setNow]=useState(new Date()),tasks=useTaskStore(s=>s.tasks),toggle=useTaskStore(s=>s.toggleTask),weather=useWeatherStore(s=>s.snapshot),load=useWeatherStore(s=>s.load),music=useMusicStore(),focus=useFocusStore();useEffect(()=>{const i=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(i)},[]);useEffect(()=>{load()},[load]);const key=localDateKey(now),list=useMemo(()=>tasks.filter(x=>x.date===key&&!x.deletedAt).slice(0,7),[tasks,key]),done=list.filter(x=>x.completed).length,first=new Date(now.getFullYear(),now.getMonth(),1).getDay(),days=new Date(now.getFullYear(),now.getMonth()+1,0).getDate();return <section className="lab-home">
 <div className="lab-room"><i className="lab-lamp"/><i className="lab-scope"/><i className="lab-flask"/><i className="lab-books"/></div><small className="lab-motto">DISCOVER<br/>PLAN<br/>FOCUS<br/>DO<br/>REPEAT</small>
 <nav className="lab-glass lab-nav">{[["⌂","HOME","/"],["△","RESEARCH","/today"],["☑","TASK","/today"],["▦","CALENDAR","/calendar"],["▤","NOTE","/notes"],["▧","PHOTO","/gallery"],["♫","MUSIC","/music"],["◎","DATA","/today"],["⌕","TOOL","/focus"],["⚙","SETTING","/settings"]].map(([i,n,p])=><button key={n} className={n==="HOME"?"active":""} onClick={()=>nav(p)}><b>{i}</b>{n}</button>)}</nav>
 <article className="lab-screen"><header>MONDAY</header><strong>{now.toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"})}</strong><b>{now.toLocaleDateString("ko-KR",{month:"long",day:"numeric",weekday:"long"})}</b><p>“A calmer mind<br/>creates<br/>a brighter day.”</p><div className="lab-dna">⌁</div><small>HUMAN<br/>BETTERMENT<br/>PROJECT</small></article>
 <article className="lab-glass lab-weather" onClick={()=>load(true)}><span>SEOUL</span><div><i>☁</i><strong>{weather?.temperature??24}°C</strong></div><b>{weather?.description??"맑음"}</b><small>H:{weather?.high??26}°　L:{weather?.low??18}°</small></article>
 <article className="lab-glass lab-music"><div className="lab-album"/><section><b>{music.title||"Focus"}</b><span>{music.artist||"Lofi Study"}</span><em><i style={{width:`${Math.max(40,music.progress)}%`}}/></em><small>1:27　　　　　　　　 -2:18</small><footer><button>◀</button><button onClick={music.togglePlay}>{music.playing?"Ⅱ":"▶"}</button><button onClick={()=>nav("/music")}>▶</button></footer></section><b>♥</b></article>
 <article className="lab-glass lab-tasks"><header><b>TODAY’S EXPERIMENT</b><span>{done}/{list.length||0}</span></header><div>{list.map(x=><button key={x.id} className={x.completed?"done":""} onClick={()=>toggle(x.id)}><i>{x.completed?"✓":""}</i>{x.title}</button>)}</div><footer>DISCIPLINE　—<br/>CREATES<br/>FREEDOM.　　⚗</footer></article>
 <article className="lab-glass lab-calendar" onClick={()=>nav("/calendar")}><header>‹　　{now.getFullYear()}. {now.getMonth()+1}　　›</header><div className="lab-week">{W.map(x=><b key={x}>{x}</b>)}</div><div className="lab-month">{Array.from({length:first}).map((_,i)=><i key={i}/>)}{Array.from({length:days},(_,i)=>i+1).map(d=><span className={d===now.getDate()?"today":""} key={d}>{d}</span>)}</div></article>
 <article className="lab-glass lab-mood"><header>MOOD STABILITY</header><div className="lab-brain">◉</div>{[["Focus",85],["Calm",72],["Energy",68],["Productivity",80]].map(([n,v])=><p key={n}><span>○ {n}</span><i><b style={{width:`${v}%`}}/></i><strong>{v}%</strong></p>)}</article>
 <article className="lab-glass lab-apps"><header>QUICK APPS</header><div>{[["▶","유튜브","/music"],["◎","인스타그램","/gallery"],["N","네이버","/"],["▲","드라이브","/gallery"],["✉","메일","/notes"],["◆","지도","/"],["◉","ChatGPT","/"],["＋","추가","/settings"]].map(([i,n,p])=><button key={n} onClick={()=>nav(p)}><b>{i}</b><span>{n}</span></button>)}</div></article>
 <aside className="lab-note">LAB NOTE<p>지금도 충분히<br/>잘하고 있어.<br/>오늘도 조금 더<br/>좋아질 거야. ♡</p></aside>
 <article className="lab-glass lab-focus"><header>FOCUS TIMER</header><strong>{focus.active?`${Math.floor(focus.remainingSeconds()/60)}:${String(focus.remainingSeconds()%60).padStart(2,"0")}`:"25:00"}</strong><button onClick={()=>focus.start(25,"Lab Focus")}>▶</button><section>◎　Focus<br/>♨　Short Break<br/>☾　Long Break</section></article>
 </section>}
