import{useEffect,useMemo,useState}from"react";import{useNavigate}from"react-router-dom";import{useTaskStore}from"../../stores/taskStore";import{useWeatherStore}from"../../stores/weatherStore";import{useMusicStore}from"../../stores/musicStore";import{useFocusStore}from"../../stores/focusStore";import{localDateKey}from"../../utils/date";
const menu=[["⌂","홈","Home","/"],["▦","일정","Schedule","/calendar"],["☑","할 일","Todo","/today"],["▤","메모","Note","/notes"],["▧","사진","Photo","/gallery"],["♫","음악","Music","/music"],["●","지도","Map","/"],["↗","링크","Link","/"],["⚙","설정","Setting","/settings"]];
export function TransitHome(){const nav=useNavigate(),[now,setNow]=useState(new Date()),tasks=useTaskStore(s=>s.tasks),toggle=useTaskStore(s=>s.toggleTask),weather=useWeatherStore(s=>s.snapshot),load=useWeatherStore(s=>s.load),music=useMusicStore(),focus=useFocusStore();useEffect(()=>{const x=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(x)},[]);useEffect(()=>{load()},[load]);const list=useMemo(()=>tasks.filter(t=>t.date===localDateKey(now)&&!t.deletedAt).slice(0,7),[tasks,now]),done=list.filter(t=>t.completed).length,first=new Date(now.getFullYear(),now.getMonth(),1).getDay(),days=new Date(now.getFullYear(),now.getMonth()+1,0).getDate();return <section className="transit-home">
 <header className="transit-message">좋은 하루가<br/>더 좋은 내일을 만든다.<small>Same Path, A Brighter You.</small></header>
 <article className="transit-clock"><small>{now.toLocaleDateString("en-CA").replaceAll("-",". ")} · {now.toLocaleDateString("en-US",{weekday:"short"}).toUpperCase()}</small><strong>{now.toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"})}</strong><b>PLAN<br/>DO<br/>FOCUS<br/>REPEAT</b></article>
 <article className="transit-weather" onClick={()=>load(true)}><i>☀</i><span>서울</span><strong>{weather?.temperature??24}°C</strong><b>{weather?.description??"맑음"}</b><small>H:{weather?.high??26}°　L:{weather?.low??18}°</small></article>
 <aside className="transit-note">오늘도<br/>수고했어.<br/>☺</aside>
 <nav className="transit-nav">{menu.map(([i,k,e,p])=><button className={e==="Home"?"active":""} onClick={()=>nav(p)} key={e}><b>{i}</b><span>{k}<small>{e}</small></span></button>)}<footer>A<br/>Better　→<br/>You<br/>Today.</footer></nav>
 <aside className="transit-next">다음역<br/><b>더 나은 나</b><small>A Brighter Me</small>→</aside>
 <article className="transit-route"><header>오늘의 노선 <small>TODAY'S ROUTE</small><span>{done}/{list.length}</span></header>{list.map((t,i)=><button className={`${t.completed?"done":""} s${i}`} onClick={()=>toggle(t.id)} key={t.id}><i>{t.completed?"✓":""}</i><b>{t.title}</b><time>{t.time||["10:00","11:00","13:00","15:00","17:00","21:00","22:00"][i]}</time></button>)}<footer>한 걸음씩,<br/>좋은 방향으로.　🚇</footer></article>
 <article className="transit-calendar" onClick={()=>nav("/calendar")}><header>‹　 {now.toLocaleDateString("ko-KR",{month:"long",year:"numeric"})}　 ›</header><div>{["일","월","화","수","목","금","토"].map(x=><b key={x}>{x}</b>)}{Array.from({length:first}).map((_,i)=><i key={i}/>)}{Array.from({length:days},(_,i)=>i+1).map(d=><span className={d===now.getDate()?"today":""} key={d}>{d}</span>)}</div><p>좋은 날이 더 많기를. ♡</p></article>
 <article className="transit-music"><header>지금 듣는 음악　♥</header><div className="transit-record"/><section><b>{music.title||"Love wins"}</b><span>{music.artist||"IU"}</span><em><i style={{width:`${Math.max(35,music.progress)}%`}}/></em><footer><button>◀</button><button onClick={music.togglePlay}>{music.playing?"Ⅱ":"▶"}</button><button onClick={()=>nav("/music")}>▶</button></footer></section></article>
 <article className="transit-shot"><header>오늘의 한 컷</header><div/><p>오늘도 멋진 하루. ♡</p></article>
 <article className="transit-apps"><header>빠른 실행 <small>QUICK ACCESS</small></header>{[["▶","유튜브","/music"],["◎","인스타그램","/gallery"],["N","네이버","/"],["✉","메일","/notes"],["▲","드라이브","/gallery"],["◆","지도","/"],["＋","추가","/settings"]].map(([i,n,p])=><button key={n} onClick={()=>nav(p)}><b>{i}</b><span>{n}</span></button>)}</article>
 <article className="transit-focus"><header>집중 타이머 <small>FOCUS TIMER</small></header><strong>{focus.active?`${Math.floor(focus.remainingSeconds()/60)}:${String(focus.remainingSeconds()%60).padStart(2,"0")}`:"25:00"}</strong><button onClick={()=>focus.start(25,"Transit Focus")}>▶</button><p>◎　Focus<br/>♨　Short Break<br/>☾　Long Break</p></article>
 <footer className="transit-line"><div>{[["기상","Wake"],["계획","Plan"],["집중","Focus"],["실행","Do"],["휴식","Rest"],["성장","Grow"],["행복","Happiness"]].map(([k,e],i)=><span key={e} className={`p${i}`}><i/>{k}<small>{e}</small></span>)}</div><b>더 멋진<br/>내일로　→</b></footer>
 </section>}
