import { useState } from "react";
import { downloadBackup, resetAllData, restoreBackup } from "../../services/backupService";
import { useMusicStore } from "../../stores/musicStore";
import { useSettingsStore } from "../../stores/settingsStore";
import { useQuickAppsStore } from "../../stores/quickAppsStore";
import { useThemeStore } from "../../stores/themeStore";
import { getTheme } from "../../themes/themeDefinitions";

const categories = ["GENERAL", "APPEARANCE", "MOTION & SOUND", "MUSIC", "TODAY", "CALENDAR", "NOTE", "GALLERY", "QUICK APPS", "DATA", "TEST MODE", "ABOUT"] as const;
type Category = (typeof categories)[number];

function Toggle({ value, onChange }: { value: boolean; onChange: (value: boolean) => void }) {
  return <button type="button" className={`toggle ${value ? "on" : ""}`} onClick={() => onChange(!value)}><i /></button>;
}

export function SettingsPage() {
  const [category, setCategory] = useState<Category>("GENERAL"); const [status, setStatus] = useState("");
  const settings = useSettingsStore(); const themeId = useThemeStore((s) => s.currentThemeId); const theme = getTheme(themeId); const music = useMusicStore(); const quickApps = useQuickAppsStore();
  const [newAppName,setNewAppName] = useState(""); const [newAppUrl,setNewAppUrl] = useState("");
  const row = (title: string, description: string, control: React.ReactNode) => <div className="setting-row"><div><b>{title}</b><span>{description}</span></div>{control}</div>;

  const importBackup = async (file?: File) => {
    if (!file) return;
    try { setStatus("복원 중…"); await restoreBackup(file); setStatus("복원 완료 · 앱을 새로고침합니다."); setTimeout(() => location.reload(), 900); } catch (error) { setStatus(error instanceof Error ? error.message : "복원 실패"); }
  };

  return <section className="page settings-page"><div className="page-head compact-head"><div><span className="kicker">SYSTEM CONTROL</span><h1>SETTINGS</h1><p>변경 사항은 즉시 저장되고 앱 전체에 적용됩니다.</p></div><span className="save-status">AUTO SAVE · ON</span></div>
    <div className="settings-layout"><aside>{categories.map((value) => <button key={value} className={category === value ? "active" : ""} onClick={() => setCategory(value)}>{value}</button>)}</aside><main>
      {category === "GENERAL" && <><h2>GENERAL</h2>{row("시작 화면", "앱 실행 후 보여줄 기본 화면", <select value={settings.startPage} onChange={(e) => settings.setSetting("startPage", e.target.value as any)}><option value="home">HOME</option><option value="today">TODAY</option><option value="last">마지막 화면</option></select>)}{row("시간 형식", "Clock과 Calendar에 공통 적용", <select value={settings.timeFormat} onChange={(e) => settings.setSetting("timeFormat", e.target.value as any)}><option value="24">24시간</option><option value="12">12시간</option></select>)}{row("UI SCALE", "아이패드 크기에 맞춰 전체 UI 조절", <select value={settings.uiScale} onChange={(e) => settings.setSetting("uiScale", Number(e.target.value) as 90|100|110)}><option value={90}>90%</option><option value={100}>100%</option><option value={110}>110%</option></select>)}{row("현재 위치 날씨", "허용 시 기기 위치로 날씨 조회", <Toggle value={settings.weatherUseCurrentLocation} onChange={(v) => settings.setSetting("weatherUseCurrentLocation", v)} />)}{!settings.weatherUseCurrentLocation && <div className="setting-row stacked"><div><b>날씨 지역</b><span>기본값은 서울입니다.</span></div><div className="location-presets">{[["서울",37.5665,126.978],["인천",37.4563,126.7052],["수원",37.2636,127.0286],["제주",33.4996,126.5312]].map(([label,lat,lon]) => <button key={String(label)} className={settings.weatherLocationLabel === label ? "active" : ""} onClick={() => { settings.setSetting("weatherLocationLabel", String(label)); settings.setSetting("weatherLatitude", Number(lat)); settings.setSetting("weatherLongitude", Number(lon)); }}>{label}</button>)}</div></div>}</>}
      {category === "APPEARANCE" && <><h2>APPEARANCE</h2>{row("현재 테마", theme.name, <span className="accent-swatch" style={{ background: theme.accent }} />)}{row("글자 크기", "본문 가독성 조절", <select value={settings.textSize} onChange={(e) => settings.setSetting("textSize", e.target.value as any)}><option value="small">작게</option><option value="default">기본</option><option value="large">크게</option></select>)}</>}
      {category === "MOTION & SOUND" && <><h2>MOTION & SOUND</h2>{row("모션 강도", "조용함 / 기본 / 생동감", <select value={settings.motionLevel} onChange={(e) => settings.setSetting("motionLevel", e.target.value as any)}><option value="quiet">조용함</option><option value="default">기본</option><option value="lively">생동감</option></select>)}{row("UI 효과음", "버튼·체크·테마 전환 효과", <Toggle value={settings.soundEnabled} onChange={(v) => settings.setSetting("soundEnabled", v)} />)}{row("효과음 볼륨", "Apple Music 음량과 별개", <input type="range" min="0" max="1" step="0.05" value={settings.soundVolume} onChange={(e) => settings.setSetting("soundVolume", Number(e.target.value))} />)}</>}
      {category === "MUSIC" && <><h2>MUSIC</h2>{row("Apple Music", music.connected ? "연결됨" : "MusicKit Developer Token 필요", <button className="primary" onClick={() => music.connect()}>{music.connected ? "CONNECTED" : "CONNECT"}</button>)}<label className="token-field">Developer Token<textarea value={music.developerToken} onChange={(e) => music.setDeveloperToken(e.target.value)} placeholder="VITE_APPLE_MUSIC_DEVELOPER_TOKEN 또는 여기 입력" /></label>{row("테마 변경 시 음악", "현재 음악 유지 / 추천 / 자동", <select value={settings.themeMusicMode} onChange={(e) => settings.setSetting("themeMusicMode", e.target.value as any)}><option value="keep">현재 음악 유지</option><option value="recommend">추천만 표시</option><option value="auto">자동 변경</option></select>)}{row("FOCUS 음악", "Focus 시작 시 테마 Focus 음악 사용", <Toggle value={settings.focusMusicEnabled} onChange={(v) => settings.setSetting("focusMusicEnabled", v)} />)}</>}
      {category === "TODAY" && <><h2>TODAY</h2>{row("DAY COMPLETE", "하루 마무리 기록 사용", <Toggle value={true} onChange={() => {}} />)}{row("Quiet Hours", `${settings.quietStart} — ${settings.quietEnd}`, <Toggle value={settings.quietHoursEnabled} onChange={(v) => settings.setSetting("quietHoursEnabled", v)} />)}<div className="setting-row stacked"><div><b>Quiet Hours 시간</b></div><div className="time-pair"><input type="time" value={settings.quietStart} onChange={(e) => settings.setSetting("quietStart", e.target.value)} /><input type="time" value={settings.quietEnd} onChange={(e) => settings.setSetting("quietEnd", e.target.value)} /></div></div></>}
      {category === "CALENDAR" && <><h2>CALENDAR</h2>{row("기본 보기", "MONTH / WEEK / DAY", <select value={settings.calendarView} onChange={(e) => settings.setSetting("calendarView", e.target.value as any)}><option value="month">MONTH</option><option value="week">WEEK</option><option value="day">DAY</option></select>)}{row("월요일 시작", "주간 기준", <Toggle value={settings.weekStartsMonday} onChange={(v) => settings.setSetting("weekStartsMonday", v)} />)}{row("FREE TIME 표시", "빈 시간 계산 표시", <Toggle value={settings.freeTimeEnabled} onChange={(v) => settings.setSetting("freeTimeEnabled", v)} />)}</>}
      {category === "NOTE" && <><h2>NOTE</h2>{row("자동 저장", "입력 후 약 450ms 뒤 저장", <Toggle value={settings.noteAutoSave} onChange={(v) => settings.setSetting("noteAutoSave", v)} />)}{row("Daily Note", "날짜별 기록 메모 사용", <Toggle value={settings.dailyNoteEnabled} onChange={(v) => settings.setSetting("dailyNoteEnabled", v)} />)}</>}
      {category === "GALLERY" && <><h2>GALLERY</h2>{row("TODAY 대표사진", "Gallery에서 하루 대표사진 선택 가능", <span>1 / DAY</span>)}{row("Wallpaper", "사진을 앱 배경으로 지정 가능", <span>SUPPORTED</span>)}</>}
      {category === "QUICK APPS" && <><h2>QUICK APPS</h2>{row("Dock 표시", "항상 / HOME만 / 자동 숨김", <select value={settings.dockMode} onChange={(e) => settings.setSetting("dockMode", e.target.value as any)}><option value="always">항상</option><option value="home">HOME만</option><option value="auto">자동 숨김</option></select>)}{row("Dock Badge", "Task / Focus 상태 표시", <Toggle value={settings.dockBadges} onChange={(v) => settings.setSetting("dockBadges", v)} />)}<div className="quick-app-editor">{quickApps.apps.map((app,index)=><div key={app.id}><span>{app.icon}</span><b>{app.name}</b><small>{app.target}</small><button onClick={()=>quickApps.move(app.id,-1)} disabled={index===0}>↑</button><button onClick={()=>quickApps.move(app.id,1)} disabled={index===quickApps.apps.length-1}>↓</button><button onClick={()=>quickApps.remove(app.id)}>×</button></div>)}<form onSubmit={(e)=>{e.preventDefault(); if(!newAppName.trim()||!newAppUrl.trim())return; quickApps.add({name:newAppName.trim(),icon:"↗",type:"web",target:newAppUrl.trim()}); setNewAppName(""); setNewAppUrl("");}}><input value={newAppName} onChange={(e)=>setNewAppName(e.target.value)} placeholder="이름"/><input value={newAppUrl} onChange={(e)=>setNewAppUrl(e.target.value)} placeholder="https://..."/><button className="primary">+ WEB APP</button></form><button onClick={quickApps.reset}>기본 Dock 복원</button></div></>}
      {category === "DATA" && <><h2>DATA</h2><div className="data-actions"><button onClick={async () => { setStatus("백업 만드는 중…"); await downloadBackup(); setStatus("백업 파일 생성 완료"); }}>백업 내보내기</button><label>백업 불러오기<input type="file" accept="application/json" onChange={(e) => importBackup(e.target.files?.[0])} /></label><button className="danger" onClick={async () => { if (!confirm("모든 Personal System 데이터를 초기화할까요?")) return; await resetAllData(); location.reload(); }}>모든 데이터 초기화</button></div>{status && <p className="status-message">{status}</p>}</>}
      {category === "TEST MODE" && <><h2>TEST MODE</h2>{row("TEST MODE", "실제 데이터는 건드리지 않고 HOME 시간·날씨 표현 테스트", <Toggle value={settings.testMode} onChange={(v) => settings.setSetting("testMode", v)} />)}{row("가상 시간", "테마 시간대 확인", <input type="time" value={settings.testTime} onChange={(e) => settings.setSetting("testTime", e.target.value)} />)}{row("가상 날씨", "HOME 날씨 아이콘 테스트", <select value={settings.testWeather} onChange={(e) => settings.setSetting("testWeather", e.target.value as any)}><option value="clear">CLEAR</option><option value="cloudy">CLOUDY</option><option value="rain">RAIN</option><option value="snow">SNOW</option></select>)}</>}
      {category === "ABOUT" && <><h2>ABOUT</h2><div className="about-card"><span>PERSONAL SYSTEM</span><strong>20 THEMES / 1 PERSONAL SPACE</strong><p>React · TypeScript · Vite · Zustand · IndexedDB · PWA · Open-Meteo · MusicKit bridge</p><small>Version 5.2.0 · 4:3 Geometry · Optimized</small></div></>}
    </main></div>
  </section>;
}
