export type ThemeDefinition={id:string;name:string;subtitle:string;accent:string;accent2:string;bg:string;panel:string;text:string;muted:string;line:string;radius:string;font:string;titleFont:string;numberFont:string;music:string;focusMusic:string;relaxMusic:string};
const t=(id:string,name:string,subtitle:string,accent:string,accent2:string,bg:string,panel:string,text:string,muted:string,line:string,radius:string,font:string,titleFont:string,numberFont:string,music:string,focusMusic:string,relaxMusic:string):ThemeDefinition=>({id,name,subtitle,accent,accent2,bg,panel,text,muted,line,radius,font,titleFont,numberFont,music,focusMusic,relaxMusic});
export const THEMES:ThemeDefinition[]=[
t("brutalist","Brutalist OS","Raw grid / bold utility","#f13a32","#fff","#111","#eeeae1","#111","#66615b","#111","0px","Arial,'Apple SD Gothic Neo',sans-serif","Impact,'Arial Black',sans-serif","Impact,sans-serif","Industrial Electronic","Hard Focus","Minimal Drone"),
t("retro-terminal","Retro Terminal","CRT command station","#65ff8f","#baffcc","#031008","#07170d","#a8ffbd","#55996a","#1d7c3a","4px","'Courier New','Apple SD Gothic Neo',monospace","Consolas,monospace","Lucida Console,monospace","Retro Synth","Terminal Focus","Green Screen Ambient"),
t("blueprint","Blueprint CAD","Technical drawing board","#d9f3ff","#76d2ff","#07345b","#083a63","#ecfaff","#9bd3ee","#5dbde9","2px","Menlo,'Apple SD Gothic Neo',monospace","'Arial Narrow',sans-serif","Monaco,monospace","Precision Electronica","CAD Focus","Cool Ambient"),
t("art-deco","Art Deco","Black, ivory and gold","#e8c46a","#fff0b8","#0d0c0a","#17140f","#fff6df","#b0a37f","#8f7538","10px","Georgia,'Apple SD Gothic Neo',serif","Copperplate,Georgia,serif","Baskerville,serif","Modern Jazz","Piano Focus","Late Night Jazz"),
t("y2k","Y2K Chrome","Glossy chrome future","#7df9ff","#ff84e8","#1b1d34","#ffffff33","#f8f9ff","#b3b9d7","#9fb5d8","28px","Trebuchet MS,'Apple SD Gothic Neo',sans-serif","Century Gothic,sans-serif","Arial Rounded MT Bold,sans-serif","Y2K Pop","Digital Focus","Dream Pop"),
t("scrapbook","Paper Scrapbook","Warm paper memories","#b65f3b","#efbb7b","#e9dcc4","#fff6e8dd","#362b24","#806f61","#c3ad8e","8px","Georgia,'Apple SD Gothic Neo',serif","Marker Felt,Comic Sans MS,cursive","American Typewriter,serif","Acoustic","Coffeehouse Focus","Soft Acoustic"),
t("moon-base","Moon Base","Monochrome lunar station","#d9e8ff","#7ea7d8","#090d13","#171e28dd","#f4f7fb","#7f8c9d","#3f4a59","18px","Helvetica,'Apple SD Gothic Neo',sans-serif","Helvetica Neue,sans-serif","Arial,sans-serif","Space Ambient","Deep Space Focus","Orbital Calm"),
t("isometric-island","Isometric Island","Playful world dashboard","#68d6a8","#ffd166","#8fd1f2","#ffffffc9","#17364a","#50758a","#5a8395","24px","Verdana,'Apple SD Gothic Neo',sans-serif","Cooper Black,Georgia,serif","Trebuchet MS,sans-serif","Game Chill","Island Study","Cozy Game"),
t("retro-pixel","Retro Pixel","Vaporwave arcade","#ff65d8","#6cf6ff","#16052a","#23103e","#fff4ff","#b998cc","#6b3f88","0px","Monaco,'Apple SD Gothic Neo',monospace","Courier New,monospace","Lucida Console,monospace","Vaporwave","Pixel Focus","Night Arcade"),
t("minimal-gallery","Minimal Gallery","Museum quiet","#111","#98704c","#f4f3ef","#fff","#171717","#77736d","#dedbd4","2px","Helvetica,'Apple SD Gothic Neo',sans-serif","Baskerville,Georgia,serif","Helvetica Neue,sans-serif","Minimal Piano","Silent Focus","Gallery Ambient"),
t("manga-panel","Manga Panel OS","Black & white story panels","#111","#ffe600","#efefeb","#fff","#0b0b0b","#666","#111","0px","Arial Black,'Apple SD Gothic Neo',sans-serif","Impact,sans-serif","Arial Black,sans-serif","Japanese Rock","Manga Study","Rainy Manga"),
t("scientific-lab","Scientific Lab OS","Research instrument UI","#5ee7ff","#9ef7d9","#07131a","#0b202a","#e9fbff","#79a6b3","#1c6070","12px","Lucida Sans,'Apple SD Gothic Neo',sans-serif","Lucida Console,monospace","Menlo,monospace","Deep Focus","Research Focus","Laboratory Ambient"),
t("racing","Racing Cockpit","Telemetry and lap data","#ff3b30","#f7d046","#08090b","#14171c","#f6f6f6","#858b95","#343943","7px","Arial Narrow,'Apple SD Gothic Neo',sans-serif","Impact,sans-serif","DIN Alternate,sans-serif","Night Drive","High BPM Focus","Road at Night"),
t("newspaper","Newspaper Editorial","Daily edition layout","#161616","#8e1b1b","#eee9dc","#f7f1e4","#191816","#69635a","#8e887d","0px","Times New Roman,'Apple SD Gothic Neo',serif","Bodoni 72 Smallcaps,Georgia,serif","Georgia,serif","Jazz & Classical","Editorial Focus","Sunday Jazz"),
t("transit","Transit Map OS","Routes, stops and connections","#1f8fff","#ffcc00","#e9edf1","#fff","#1b2430","#697887","#b8c3cd","16px","Arial,'Apple SD Gothic Neo',sans-serif","Helvetica Neue,sans-serif","Arial,sans-serif","City Pop","Commute Focus","Night Transit"),
t("fantasy","Fantasy Codex","Quest book and runes","#9c6b2f","#d7b56d","#2a1f16","#dfcba3","#362718","#776244","#8c6f43","12px","Palatino,'Apple SD Gothic Neo',serif","Papyrus,fantasy","Book Antiqua,serif","Fantasy OST","Fantasy Study","Peaceful Fantasy"),
t("modular-synth","Modular Synth OS","Patch cables and sequencers","#f6a623","#61dafb","#111214","#1b1e22","#f7f3e8","#8f949b","#43474e","5px","Monaco,'Apple SD Gothic Neo',monospace","Eurostile,sans-serif","Lucida Console,monospace","Analog Electronic","Sequencer Focus","Warm Modular"),
t("gothic","Gothic Stained Glass","Dark cathedral light","#d2af63","#8e1b4c","#09070a","#151017","#eee5d7","#917f86","#513b45","3px","Georgia,'Apple SD Gothic Neo',serif","Didot,Georgia,serif","Baskerville,serif","Dark Classical","Cathedral Focus","Candlelight"),
t("medical","Medical Scanner OS","Clinical scanner station","#8ff0c6","#8bd4ff","#0c1518","#132125","#e6f8f2","#7e9f98","#2c4e4a","14px","Arial,'Apple SD Gothic Neo',sans-serif","Helvetica Neue,sans-serif","Menlo,monospace","Clinical Ambient","Clean Focus","Recovery Ambient"),
t("luxury-watch","Luxury Watch OS","Chronograph precision","#c8a55a","#e9d8a8","#090909","#121212","#f2efe8","#8e887f","#3a352d","999px","Georgia,'Apple SD Gothic Neo',serif","Didot,Georgia,serif","Baskerville,serif","Lounge","Minimal Piano","Soft Jazz")];
export const DEFAULT_THEME=THEMES.find((x)=>x.id==="moon-base")!;
export function getTheme(id:string){return THEMES.find((x)=>x.id===id)??DEFAULT_THEME;}
